services:
  web:
    image: ghcr.io/dreamgear/star-wars-explorer:latest
    container_name: star-wars-explorer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.starwars.rule=Host(`one.dreamgearweb.com`)"
      - "traefik.http.routers.starwars.entrypoints=websecure"
      - "traefik.http.routers.starwars.tls.certresolver=myresolver"
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: true
